### ISSUE TITLE
Open a third-party page in Iframe

### ISSUE THREAD

**Issue by Aroxed** [krakenjs/zoid#262]
Hello.
Is there a way to open and have access to an random page (like www.facebook.com or cnn.com) in Iframe using zoid? 

Thanks.

**Comment by bluepnume** [comment]
The page you load **must**:

1. Consent to being used as an iframe (so not contain any x-frame headers, csp headers, or javascript that would block it being used as an iframe)
2. Load your zoid component in the child, so that communication can happen between the child and the parent.

For those reasons, zoid is most useful when you own the child frame and you want to expose it as a zoid component. Third-party pages are off-limits unless they explicitly load zoid too.
