### ISSUE TITLE
Optionally allow multiple ports on the same domain

### ISSUE THREAD

**Issue by bluepnume** [krakenjs/zoid#64]
For when a page redirects to an app on the same domain with a different port. Will also need post-robot changes.

**Comment by stefan2410** [comment]
In this issue, a question ( I like your component but I have not used it yet, so maybe it is  a naive question) 
One case that I want to use  the component  is to open a page in the same domain. The reason is that the page in the iframe will be developed with different technology. In this case, and if we use cookie, (or httponly header) for authentication, is it possible to be transferred transferrent with the httprequest ?  
I use ASP.Net Core but  many views are essentially mini-spas in JavaScript and with different thechnologies.  e.g. a  view with vanilla javascript or web framework, to load the xcomponent with a Razor page.

**Comment by bluepnume** [comment]
This is a perfect example of a good use-case for xcomponent -- sharing functionality without having to use the same technology across the entire site.

Can you clarify the question about authentication? If you're loading an iframe, the request to the server should receive any cookies set on the browser, so it should be no different to an ordinary page load.

**Comment by stefan2410** [comment]
Yes, I wanted a confirmation because I have not use it till now. but I like very much the idea, super useful.
 I could  open a Razor page or a Vue.js from another web framework .
Add, please in your web frameworks support  the Aurelia also. I think it will be easy.
thanks
